sudo: required
services:
  - docker


before_install:
  - docker build -t mmarchett/docker-multiservice -f Dockerfile.dev .

script:
  - docker run -e CI=true mmarchett/docker-multiservice npm run test -- --coverage